resources:
  - name: testingUtilsGit
    type: GitRepo
    configuration:
      path: jfrog/jfrog-testing-infra
      gitProvider: github
      buildOn:
        tagCreate: true
        commit: false

pipelines:
  - name: build_testing_infra
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: releases-docker.jfrog.io/jfrog-ecosystem-integration-env
            tag: 1.0.0
      environmentVariables:
        readOnly:
          CI: "true"
          JFROG_CLI_BUILD_NAME: $pipeline_name
          JFROG_CLI_BUILD_NUMBER: $run_number

    steps:
      - name: publish
        type: Bash
        configuration:
          inputResources:
            - name: testingUtilsGit
          integrations:
            - name: ojo
        execution:
          onExecute:
            - cd $res_testingUtilsGit_resourcePath
            - curl -fL https://getcli.jfrog.io | sh && chmod +x ./jfrog
            - ./jfrog rt c ojo --url $int_ojo_rt_url --access-token=$int_ojo_rt_token
            - ./jfrog rt gradle clean aP
            - ./jfrog rt bp